const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={book:'i-book',trophy:'i-trophy',medal:'i-medal',ball:'i-ball',people:'i-people',users:'i-users',file:'i-file',heart:'i-heart',grid:'i-grid',pin:'i-pin'};
const icon=n=>`<svg aria-hidden="true"><use href="#${icons[n]||'i-grid'}"/></svg>`;
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function showProgram(id){const p=SEL.programs.find(x=>x.id===id);if(!p)return;$('#dialogBody').innerHTML=`<div class="dialog-top tone-${p.tone}">${p.logo?`<img src="assets/${p.logo}" alt="">`:icon(p.icon)}<span>${p.tag}</span></div><div class="dialog-content"><h2>${p.name}</h2><p>${p.description}</p><div class="dialog-highlight">${p.highlight}</div><small>Conteúdo demonstrativo. Consulte o portal oficial para informações vigentes.</small><a class="primary-btn" href="${p.url}" target="_blank" rel="noreferrer">${p.action} ${icon('file')}</a></div>`;$('#programDialog').showModal()}
function programCard(p){return `<article class="program-card tone-${p.tone} reveal"><div class="program-icon">${p.logo?`<img src="assets/${p.logo}" alt="">`:icon(p.icon)}</div><span>${p.tag}</span><h3>${p.name}</h3><p>${p.description}</p><strong>${p.highlight}</strong><button data-program="${p.id}">${p.action}<svg><use href="#i-arrow"/></svg></button></article>`}
function renderFeatured(){$('#featuredPrograms').innerHTML=SEL.programs.slice(0,3).map(programCard).join('')}
function renderPrograms(q=''){const n=SEL.normalize(q);const list=SEL.programs.filter(p=>SEL.normalize(`${p.name} ${p.tag} ${p.description}`).includes(n));$('#programList').innerHTML=list.length?list.map(programCard).join(''):'<p class="empty">Nenhum programa encontrado.</p>';observeReveals()}
function renderData(){const total=SEL.support.reduce((s,x)=>s+x.investment,0),max=Math.max(...SEL.support.map(x=>x.investment));$('#dataContent').innerHTML=`<div class="data-hero reveal"><div><span>COMPETE BRASÍLIA</span><h2>Resultados que atravessam fronteiras</h2><p>Apoio demonstrativo a atletas e paratletas em competições.</p></div><div class="donut" style="--p:72"><strong data-count="1773">0</strong><small>beneficiados</small></div></div><div class="data-kpis reveal"><article><small>Investimento</small><strong>R$ 2,91 mi</strong><span>Total demonstrativo</span></article><article><small>Medalhas</small><strong data-count="350">0</strong><span>Referência visual</span></article><article><small>Apoios</small><strong data-count="3">0</strong><span>Modalidades de transporte</span></article></div><article class="chart-card reveal"><div class="section-head"><div><small>DISTRIBUIÇÃO</small><h2>Investimento por apoio</h2></div></div><div class="bars">${SEL.support.map(x=>`<div><div class="bar-head"><span>${x.name}</span><strong>${money(x.investment)}</strong></div><div class="track"><i style="--w:${x.investment/max*100}%;background:${x.color}"></i></div><small>${x.people.toLocaleString('pt-BR')} atendimentos</small></div>`).join('')}</div><p class="source-note">Valores demonstrativos, sem integração em tempo real.</p></article><div class="split-cards reveal"><article><span>12</span><h3>COPs</h3><p>Unidades em diferentes regiões do DF.</p></article><article><span>2 mil+</span><h3>Escola de Esportes</h3><p>Alunos no cenário demonstrativo.</p></article></div>`;observeReveals()}
let category='todos';
function renderModalities(){const q=SEL.normalize($('#modalitySearch')?.value||'');const list=SEL.general.filter(x=>(category==='todos'||x.category===category)&&SEL.normalize(x.name).includes(q));$('#modalityList').innerHTML=list.length?list.map(x=>`<article class="modality-item"><span>${icon('ball')}</span><strong>${x.name}</strong><small>${x.category}</small></article>`).join(''):'<p class="empty">Nenhuma modalidade encontrada.</p>'}
function setupModalities(){const labels={todos:'Todas',coletivas:'Coletivas',aquaticas:'Aquáticas',lutas:'Lutas',ginasticas:'Ginásticas','bem-estar':'Bem-estar',individuais:'Individuais'};$('#modalityFilters').innerHTML=Object.entries(labels).map(([id,label])=>`<button class="${id==='todos'?'active':''}" data-category="${id}">${label}</button>`).join('');$('#inclusiveList').innerHTML=SEL.inclusive.map(x=>`<article class="modality-item inclusive">${icon('heart')}<strong>${x}</strong></article>`).join('');renderModalities()}
function renderSchool(){$('#schoolList').innerHTML=SEL.school.map(x=>`<article class="vacancy reveal">${icon('ball')}<h3>${x.name}</h3><div><strong>${x.vacancies}</strong><span>vagas</span></div></article>`).join('');observeReveals()}
let spaceType='cops';
function renderSpaces(){const sources={cops:SEL.centers.map(x=>`COP ${x}`),venues:SEL.venues,fields:SEL.fields.map(x=>`Campo - ${x}`)};$('#spaceList').innerHTML=sources[spaceType].map(x=>`<div class="space-item">${icon('pin')}<span>${x}</span></div>`).join('')}
function setupSpaces(){$('#mapFrame').src=SEL.mapURL;$('#spaceFilters').innerHTML=[['cops','12 COPs'],['venues','8 espaços'],['fields','8 campos']].map(([id,l])=>`<button data-space="${id}" class="${id==='cops'?'active':''}">${l}</button>`).join('');renderSpaces()}
function renderTeam(){$('#teamList').innerHTML=SEL.team.map((x,i)=>`<article class="team-card reveal"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${x.name}</h3><p>${x.role}</p></div></article>`).join('');observeReveals()}
function animateCounts(root=document){if(matchMedia('(prefers-reduced-motion: reduce)').matches){$$('[data-count]',root).forEach(el=>el.textContent=Number(el.dataset.count).toLocaleString('pt-BR')+(el.dataset.suffix||''));return}$$('[data-count]',root).forEach(el=>{if(el.dataset.done)return;el.dataset.done='1';const end=+el.dataset.count,start=performance.now();function tick(now){const p=Math.min((now-start)/900,1),v=Math.round(end*(1-Math.pow(1-p,3)));el.textContent=v.toLocaleString('pt-BR')+(el.dataset.suffix||'');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
let revealObserver;function observeReveals(){if(!('IntersectionObserver'in window)||matchMedia('(prefers-reduced-motion: reduce)').matches){$$('.reveal').forEach(x=>x.classList.add('shown'));return}if(!revealObserver)revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('shown');animateCounts(e.target);revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal:not(.shown)').forEach(x=>revealObserver.observe(x))}
function closeMenu(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false')}
function route(){const name=location.hash.slice(1)||'inicio',safe=$(`[data-view="${name}"]`)?name:'inicio';$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===safe));$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===safe));$('.app-shell').classList.toggle('map-mode',safe==='espacos');closeMenu();scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setTimeout(()=>{observeReveals();animateCounts($(`[data-view="${safe}"]`))},60)}
renderFeatured();renderPrograms();renderData();setupModalities();renderSchool();setupSpaces();renderTeam();route();observeReveals();
addEventListener('hashchange',route);document.addEventListener('click',e=>{const p=e.target.closest('[data-program]');if(p)showProgram(p.dataset.program);const g=e.target.closest('[data-go]');if(g)location.hash=g.dataset.go;const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;$$('[data-category]').forEach(b=>b.classList.toggle('active',b===c));renderModalities()}const s=e.target.closest('[data-space]');if(s){spaceType=s.dataset.space;$$('[data-space]').forEach(b=>b.classList.toggle('active',b===s));renderSpaces()}});
$('#programSearch').addEventListener('input',e=>renderPrograms(e.target.value));$('#modalitySearch').addEventListener('input',renderModalities);$('#menuBtn').addEventListener('click',()=>{$('#drawer').classList.add('open');$('#scrim').classList.add('open');$('#menuBtn').setAttribute('aria-expanded','true')});$('#menuClose').addEventListener('click',closeMenu);$('#scrim').addEventListener('click',closeMenu);$('.dialog-close').addEventListener('click',()=>$('#programDialog').close());$('#programDialog').addEventListener('click',e=>{if(e.target===$('#programDialog'))$('#programDialog').close()});$('#spaceInfoBtn').addEventListener('click',()=>$('#spaceSheet').classList.add('open'));$('#spaceClose').addEventListener('click',()=>$('#spaceSheet').classList.remove('open'));addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();$('#spaceSheet').classList.remove('open')}});
