const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={book:'i-book',trophy:'i-trophy',medal:'i-medal',ball:'i-ball',people:'i-people',file:'i-file',heart:'i-heart'};
const icon=n=>`<svg aria-hidden="true"><use href="#${icons[n]||'i-grid'}"/></svg>`;
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function programImage(p){return p.logo?`<img src="assets/${p.logo}" alt="">`:icon(p.icon)}
function showProgram(id){const p=SEL.programs.find(x=>x.id===id);if(!p)return;$('#dialogBody').innerHTML=`${p.photo?`<img class="dialog-hero" src="assets/${p.photo}" alt="Imagem de ${p.name}">`:''}<div class="dialog-content">${p.logo?`<img class="dialog-logo" src="assets/${p.logo}" alt="Marca ${p.name}">`:''}<h2>${p.name}</h2><strong>${p.tag}</strong><p>${p.description}</p>${p.metric?`<div class="data-kpis"><div><strong>${p.metric}</strong><span>${p.metricLabel}</span></div><div><strong>${p.period}</strong><span>Período de referência</span></div></div>`:''}<a class="primary-btn" href="${p.url}" target="_blank" rel="noreferrer">Acessar página oficial ${icon('file')}</a></div>`;$('#programDialog').showModal()}
function renderFeatured(){const ps=SEL.programs.slice(0,2);$('#featuredPrograms').innerHTML=ps.map(p=>`<button class="feature-card ${p.color==='green'?'green':''}" data-program="${p.id}"><img class="photo" src="assets/${p.photo}" alt=""><div class="feature-copy">${icon(p.icon)}<h3>${p.name}</h3><p>${p.tag}</p></div><span class="round-arrow"><svg><use href="#i-arrow"/></svg></span></button>`).join('')}
function renderPrograms(q=''){const ps=SEL.filterPrograms(q);$('#programList').innerHTML=ps.length?ps.map(p=>`<button class="program-row" data-program="${p.id}"><span class="picon">${programImage(p)}</span><span><h3>${p.name}</h3><p>${p.tag}</p></span><svg class="arrow"><use href="#i-arrow"/></svg></button>`).join(''):`<p class="empty">Nenhum programa encontrado.</p>`}
function renderData(){const max=Math.max(...SEL.support.map(x=>x.investment));$('#dataContent').innerHTML=`<article class="data-card"><div class="section-head"><h2>Compete Brasília</h2><span class="subnote">1º semestre de 2024</span></div><div class="data-kpis"><div><strong>1.773</strong><span>Beneficiados</span></div><div><strong>R$ 2,91 mi</strong><span>Investimento total</span></div></div><h3>Investimento por apoio</h3><div class="bars">${SEL.support.map(x=>`<div><div class="bar-head"><span>${x.name}</span><strong>${money(x.investment)}</strong></div><div class="track"><i style="width:${x.investment/max*100}%"></i></div><small>${x.people} atendimentos</small></div>`).join('')}</div><p class="subnote">Dados históricos do protótipo em PDF.</p></article><article class="data-card"><div class="section-head"><h2>Escola de Esportes</h2><span class="subnote">2º semestre de 2025</span></div><div class="data-kpis"><div><strong>2 mil+</strong><span>Alunos beneficiados</span></div><div><strong>8</strong><span>Modalidades destacadas</span></div></div><div class="modalities">${SEL.modalities.map(x=>`<span>${x}</span>`).join('')}</div></article>`}
function setupSpaces(){$('#mapFrame').src=SEL.mapURL}
function closeMenu(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false')}
function route(){const name=location.hash.slice(1)||'inicio';const safe=$(`[data-view="${name}"]`)?name:'inicio';$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===safe));$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===safe));$('.app-shell').classList.toggle('map-mode',safe==='espacos');closeMenu();scrollTo({top:0,behavior:'smooth'})}
renderFeatured();renderPrograms();renderData();setupSpaces();route();
addEventListener('hashchange',route);document.addEventListener('click',e=>{const p=e.target.closest('[data-program]');if(p)showProgram(p.dataset.program);const g=e.target.closest('[data-go]');if(g)location.hash=g.dataset.go;const f=e.target.closest('[data-filter]');if(f){spaceType=f.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===f));renderSpaces()}});
$('#programSearch').addEventListener('input',e=>renderPrograms(e.target.value));$('#menuBtn').addEventListener('click',()=>{$('#drawer').classList.add('open');$('#scrim').classList.add('open');$('#menuBtn').setAttribute('aria-expanded','true')});$('#menuClose').addEventListener('click',closeMenu);$('#scrim').addEventListener('click',closeMenu);$('.dialog-close').addEventListener('click',()=>$('#programDialog').close());$('#programDialog').addEventListener('click',e=>{if(e.target===$('#programDialog'))$('#programDialog').close()});addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});

